# Generated by Django 4.2.20 on 2025-06-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='frm',
            field=models.CharField(db_collation='utf8mb4_bin', max_length=100),
        ),
        migrations.AlterField(
            model_name='requests',
            name='to',
            field=models.CharField(db_collation='utf8mb4_bin', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(db_collation='utf8mb4_bin', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(db_collation='utf8mb4_bin', max_length=100),
        ),
    ]
