# Generated by Django 4.2.20 on 2025-06-21 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nim', '0002_alter_requests_frm_alter_requests_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='frm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='Nim.users'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='Nim.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(db_collation='utf8mb4_bin', max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='requests',
            unique_together={('frm', 'to')},
        ),
    ]
