# Generated by Django 4.2.20 on 2025-06-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nim', '0004_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='turn',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
